project_id = "pbemnbaapzuwimlwelut"

[functions.revenuecat-webhook]
verify_jwt = false

[functions.expire-trials]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false